-- 2022년 1월의 도서 판매 데이터
-- 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가

SELECT
    A.AUTHOR_ID, A.AUTHOR_NAME, AB.CATEGORY, 
    AB.TOTAL_SALES
FROM AUTHOR A
JOIN (
    SELECT 
    B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * BS.SALES) TOTAL_SALES
    FROM BOOK B
    JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE >= DATE '2022-01-01'
    AND BS.SALES_DATE < DATE '2022-02-01'
    GROUP BY B.AUTHOR_ID, B.CATEGORY
    ) AB
    ON A.AUTHOR_ID = AB.AUTHOR_ID
ORDER BY AB.AUTHOR_ID ASC, AB.CATEGORY DESC
    