-- PARENT_ID == NULL >> (1)
-- PARENT_ID == (1)  >> (2)
-- PARENT_ID == (2)  >> (3)

-- (1)
# SELECT ID
# FROM ECOLI_DATA
# WHERE PARENT_ID IS NULL

-- (2)
# SELECT ID
# FROM ECOLI_DATA
# WHERE PARENT_ID IN (
#     SELECT ID
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NULL
# )

SELECT 
    ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    )
)
ORDER BY ID