-- 2. 1번 서브 테이블의 ID를 제외한 ID에 해당하는 데이터 출력
SELECT
    ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II
WHERE ITEM_ID NOT IN (
    SELECT A.ITEM_ID
    FROM ITEM_TREE A
    JOIN ITEM_TREE B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
    GROUP BY A.ITEM_ID
) 
ORDER BY ITEM_ID DESC


-- 1. 부모 아이디로 자신의 ID가 없는 것들의 ID
# SELECT A.ITEM_ID
# FROM ITEM_TREE A
# JOIN ITEM_TREE B
# ON A.ITEM_ID = B.PARENT_ITEM_ID
# GROUP BY A.ITEM_ID