SELECT 
    ED.ID, 
    CASE 
    WHEN C.CHILD_COUNT IS NULL THEN 0
    ELSE C.CHILD_COUNT
    END AS CHILD_COUNT
FROM ECOLI_DATA ED 
LEFT JOIN (
    SELECT 
        PARENT_ID ID, COUNT(*) CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
    ORDER BY PARENT_ID
) C
ON ED.ID = C.ID
ORDER BY ID