-- 세단, SUV인 차량
-- SELECT
--     CAR_ID
-- FROM CAR_RENTAL_COMPANY_CAR
-- WHERE CAR_TYPE IN ('세단', 'SUV')

-- -- 2022-11-01 부터 2022-11-30까지 대여 기록이 없는 차량
-- SELECT DISTINCT H1.CAR_ID
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H1
-- WHERE NOT EXISTS (
--     SELECT 1
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
--     WHERE H1.CAR_ID = H2.CAR_ID
--       AND H2.START_DATE <= DATE '2022-11-30'
--       AND H2.END_DATE >= DATE '2022-11-01'
-- )

-- 30일간의 대여 금액이 50만원 ~ 200만원 미만인 자동차
SELECT
    CAR_ID,
    CAR_TYPE,
    FEE
FROM (
    SELECT
        C.CAR_ID, 
        C.CAR_TYPE,
        ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        ON C.CAR_TYPE = P.CAR_TYPE
    JOIN (
        SELECT DISTINCT H1.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H1
        WHERE NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
            WHERE H1.CAR_ID = H2.CAR_ID
              AND H2.START_DATE <= DATE '2022-11-30'
              AND H2.END_DATE >= DATE '2022-11-01'
        )
    ) H
        ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
      AND P.DURATION_TYPE = '30일 이상'
) T
WHERE FEE >= 500000
  AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
    