SELECT
    I.FOOD_TYPE,
    I.REST_ID,
    I.REST_NAME,
    I.FAVORITES
FROM REST_INFO I
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) M
ON I.FOOD_TYPE = M.FOOD_TYPE
AND I.FAVORITES = M.MAX_FAV
ORDER BY I.FOOD_TYPE DESC;
