SELECT
    RI.FOOD_TYPE,
    RI.REST_ID,
    RI.REST_NAME,
    RI.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) V
ON RI.FOOD_TYPE = V.FOOD_TYPE
AND RI.FAVORITES = V.FAVORITES
ORDER BY RI.FOOD_TYPE DESC;