SELECT
    RI.FOOD_TYPE,
    RI.REST_ID,
    RI.REST_NAME,
    RI.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT 
        MAX(FAVORITES) FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) V
ON RI.FAVORITES = V.FAV
GROUP BY RI.FOOD_TYPE
ORDER BY RI.FOOD_TYPE DESC