-- 개체의 크기를 내림차순으로 정렬
# SELECT
#     ID, 
#     NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE
# FROM ECOLI_DATA
# ORDER BY SIZE_OF_COLONY ASC

SELECT
    ED.ID, 
    CASE 
    WHEN S.SIZE = 1 THEN 'CRITICAL'
    WHEN S.SIZE = 2 THEN 'HIGH'
    WHEN S.SIZE = 3 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM ECOLI_DATA ED
JOIN (
    SELECT
        ID, 
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE
    FROM ECOLI_DATA
    ORDER BY SIZE_OF_COLONY ASC
) S 
ON ED.ID = S.ID
ORDER BY ID