SELECT
    GU.USER_ID, 
    GU.NICKNAME, 
    GU.CITY || ' ' || GU.STREET_ADDRESS1 || ' ' || GU.STREET_ADDRESS2 AS 전체주소, 
    SUBSTR(GU.TLNO, 1, 3) || '-' || 
    SUBSTR(GU.TLNO, 4, 4) || '-' || SUBSTR(GU.TLNO, 8, 4) AS 전화번호
FROM USED_GOODS_USER GU
JOIN (SELECT WRITER_ID, COUNT(*) AS POST_CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3) PC
     ON GU.USER_ID = PC.WRITER_ID
ORDER BY GU.USER_ID DESC