SELECT
    AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
JOIN (SELECT ANIMAL_ID
     FROM ANIMAL_OUTS
     WHERE UPPER(SEX_UPON_OUTCOME) LIKE '%SPAYED%' 
     OR UPPER(SEX_UPON_OUTCOME) LIKE '%NEUTERED%'
) AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE UPPER(AI.SEX_UPON_INTAKE) LIKE '%INTACT%'
ORDER BY AI.ANIMAL_ID