SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
WHERE UPPER(AI.SEX_UPON_INTAKE) LIKE '%INTACT%'
  AND AI.ANIMAL_ID IN (
      SELECT AO.ANIMAL_ID
      FROM ANIMAL_OUTS AO
      WHERE UPPER(AO.SEX_UPON_OUTCOME) LIKE '%SPAYED%'
         OR UPPER(AO.SEX_UPON_OUTCOME) LIKE '%NEUTERED%'
  )
ORDER BY AI.ANIMAL_ID;
