-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계

SELECT
    EXTRACT(YEAR FROM S.SALES_DATE) YEAR, 
    EXTRACT(MONTH FROM S.SALES_DATE) MONTH, 
    U.GENDER, 
    COUNT(DISTINCT U.USER_ID) USERS
FROM ONLINE_SALE S
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM S.SALES_DATE), 
    EXTRACT(MONTH FROM S.SALES_DATE), 
    U.GENDER
ORDER BY YEAR, MONTH, GENDER