-- 코드를 입력하세요
SELECT ANIMAL_TYPE, COUNT(*) AS count
FROM ANIMAL_INS
WHERE UPPER(ANIMAL_TYPE) = 'CAT'
    OR UPPER(ANIMAL_TYPE) = 'DOG'
GROUP BY ANIMAL_TYPE
ORDER BY 
    CASE UPPER(ANIMAL_TYPE)
        WHEN 'CAT' THEN 1
        ELSE 2
    END