-- SELECT
--     CH.CAR_ID, 
--     CASE  
--         WHEN CH.END_DATE <= DATE '2022-10-16' THEN '대여 가능'
--         WHEN DATE '2022-10-16' <= CH.END_DATE THEN '대여중'
--         ELSE '대여 가능'
--     END AS AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
-- JOIN (SELECT CAR_ID, MAX(END_DATE) AS END_DATE
--      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--      GROUP BY CAR_ID) MS ON CH.CAR_ID = MS.CAR_ID
-- WHERE CH.END_DATE = MS.END_DATE
-- ORDER BY CH.CAR_ID DESC

SELECT CAR_ID, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE > DATE '2022-10-16' OR END_DATE < DATE '2022-10-16'
ORDER BY CAR_ID DESC, END_DATE DESC