-- 트럭인 자동차의 대여 기록 0
-- 대여 기록 별 대여 금액
-- 대여 기록 ID, 금액 리스트 출력
-- 대여 금액 기준 내림차순, 대역 기록 ID 오름차순

 SELECT
    H.HISTORY_ID,
    FLOOR(
        C.DAILY_FEE
        * (TRUNC(H.END_DATE - H.START_DATE) + 1)
        * (1 - NVL(P.DISCOUNT_RATE, 0) / 100)
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
  ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON C.CAR_TYPE = P.CAR_TYPE
 AND (
        (TRUNC(H.END_DATE - H.START_DATE) + 1 >= 90 AND P.DURATION_TYPE = '90일 이상')
     OR (TRUNC(H.END_DATE - H.START_DATE) + 1 >= 30 AND TRUNC(H.END_DATE - H.START_DATE) + 1 < 90 AND P.DURATION_TYPE = '30일 이상')
     OR (TRUNC(H.END_DATE - H.START_DATE) + 1 >= 7  AND TRUNC(H.END_DATE - H.START_DATE) + 1 < 30 AND P.DURATION_TYPE = '7일 이상')
 )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC