
SELECT FH.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF 
    GROUP BY FLAVOR) FH
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY 
    GROUP BY FLAVOR) J
ON FH.FLAVOR = J.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY SUM(FH.TOTAL + J.TOTAL) DESC
LIMIT 3

