SELECT 
    AD.APNT_NO, P.PT_NAME, P.PT_NO, AD.MCDP_CD, AD.DR_NAME, AD.APNT_YMD
FROM (
    SELECT A.APNT_NO, A.PT_NO, A.MCDP_CD, A.APNT_YMD, D.DR_NAME
    FROM APPOINTMENT A
    JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
    WHERE TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
    AND A.APNT_CNCL_YN = 'N') AD
JOIN PATIENT P ON P.PT_NO = AD.PT_NO
ORDER BY AD.APNT_YMD ASC