-- 0 ~ 23 각 시간대별 입양 건 수 조회
-- 시간대 순으로 정렬
SELECT 
    H.HOUR, 
    COUNT(HH.HOUR) COUNT
FROM 
    (SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24) H
LEFT JOIN
    (SELECT 
        TO_CHAR(DATETIME, 'HH24') HOUR
    FROM ANIMAL_OUTS) HH ON H.HOUR = HH.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR

