-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일
SELECT 
    MP.MEMBER_NAME, 
    R.REVIEW_TEXT, 
    TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW R ON MP.MEMBER_ID = R.MEMBER_ID
WHERE MP.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    FETCH FIRST 1 ROW ONLY)
ORDER BY REVIEW_DATE, REVIEW_TEXT
