-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 리뷰 개수를 비교해서 가장 많은 수를 가진 회원 이름 필요
SELECT
    MP.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW R
JOIN (
    SELECT MEMBER_ID,COUNT(*) CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
    FETCH FIRST 1 ROW ONLY
) M
ON M.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE MP
ON MP.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT