-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 리뷰 개수를 비교해서 가장 많은 수를 가진 회원 이름 필요
SELECT
    M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM REST_REVIEW R
JOIN (
    SELECT RR.MEMBER_ID, MP.MEMBER_NAME, COUNT(*) CNT
    FROM REST_REVIEW RR
    JOIN MEMBER_PROFILE MP
    ON RR.MEMBER_ID = MP.MEMBER_ID
    GROUP BY RR.MEMBER_ID, MP.MEMBER_NAME
    ORDER BY CNT DESC
    FETCH FIRST 1 ROW ONLY
) M
ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT