SELECT
    EXTRACT(MONTH FROM CH.START_DATE) AS MONTH,
    CH.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
JOIN (
    SELECT CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) CN ON CH.CAR_ID = CN.CAR_ID
WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
GROUP BY CH.CAR_ID, EXTRACT(MONTH FROM CH.START_DATE)
HAVING COUNT(*) >= 0
ORDER BY MONTH ASC, CH.CAR_ID DESC