-- 상품 카테고리 코드(PRODUCT_CODE 앞 2자리) 별 상품 개수를 출력
-- 상품 카테고리 코드 순
SELECT SUBSTRING(PRODUCT_CODE, 1, 2) as CATEGORY, 
    COUNT(SUBSTRING(PRODUCT_CODE, 1, 2)) as PRODUCTS
FROM PRODUCT
GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2)