SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    D.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
             MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA
      GROUP BY YEAR) D ON YEAR(E.DIFFERENTIATION_DATE) = D.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC
