-- 자동차 종류가 '세단'인 자동차들 중 10월에 대여를 시작한 기록이 있는 자동차 ID 리스트
-- ID는 중복 X
SELECT CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING (CAR_ID)
WHERE CAR_TYPE = '세단'
    AND TO_CHAR(START_DATE, 'YYYY-MM') >= '2022-10'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC