-- 각 종류별 최댓값 구하기
-- 10cm 이하의 물고기는 10cm로 취급

SELECT
    COUNT(*) FISH_COUNT, 
    MAX(LENGTH) MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE ASC



